// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXZg6emCIvlPjwg2bpfl4ddbZYRITzNhw',
    appId: '1:1017638934197:web:b9af110c0c1ae10bf110fc',
    messagingSenderId: '1017638934197',
    projectId: 'interviya-8f353',
    authDomain: 'interviya-8f353.firebaseapp.com',
    storageBucket: 'interviya-8f353.firebasestorage.app',
    measurementId: 'G-BT40N2305Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1C-W15tT1YwgwIkxa2deNgxWMojlt6h0',
    appId: '1:1017638934197:android:61a27fd2f9df9715f110fc',
    messagingSenderId: '1017638934197',
    projectId: 'interviya-8f353',
    storageBucket: 'interviya-8f353.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4oot1YKBk2K9k44Yv49Ah-p_cS0VMyVs',
    appId: '1:1017638934197:ios:1e1e080e4d83580ef110fc',
    messagingSenderId: '1017638934197',
    projectId: 'interviya-8f353',
    storageBucket: 'interviya-8f353.firebasestorage.app',
    iosBundleId: 'com.interviya.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4oot1YKBk2K9k44Yv49Ah-p_cS0VMyVs',
    appId: '1:1017638934197:ios:aa927be7e355c5dcf110fc',
    messagingSenderId: '1017638934197',
    projectId: 'interviya-8f353',
    storageBucket: 'interviya-8f353.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXZg6emCIvlPjwg2bpfl4ddbZYRITzNhw',
    appId: '1:1017638934197:web:98811bc2e58653aaf110fc',
    messagingSenderId: '1017638934197',
    projectId: 'interviya-8f353',
    authDomain: 'interviya-8f353.firebaseapp.com',
    storageBucket: 'interviya-8f353.firebasestorage.app',
    measurementId: 'G-XJQPWLB4SG',
  );
}
